### PR TITLE
0.9.x: fixing handler import for cache overflow

### PR DESCRIPTION
**Pull request by rubbish**
We ran into this on one of our environments today after upgrading to 0.9.15:

```
04/12/2015 15:48:38 :: [console] Exception in cacheFull event handler: args=() kwargs={}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/graphite/lib/carbon/client.py", line 114, in queueFullCallback
    events.cacheFull()
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/opt/graphite/lib/carbon/events.py", line 32, in <lambda>
    cacheFull.addHandler(lambda: carbon.instrumentation.increment('cache.overflow'))
exceptions.NameError: global name 'carbon' is not defined
```

Changing the handler package fixed it.

### CODE REVIEW

**Comment by bmhatfield** [comment]
Looks great, and all of the checks passed except for the python2.6/twisted problem, which isn't this PR's fault.

**Comment by gretel** [comment]
applying https://github.com/graphite-project/carbon/commit/2af22b3e36fc4a212c1ffecb0c16916cd0f50f31leads to `exceptions.AttributeError: 'module' object has no attribute 'instrumentation'` instead. i tried merging from `master` but could not find any relevant changes.

**Comment by rubbish** [comment]
@gretel hmm... I'm going to have to check it out. My python-fu isn't that strong and I thought I had the right thing.

**Comment by gretel** [comment]
:hourglass_flowing_sand:

**Comment by frlinux** [comment]
+1 I can confirm this is still an issue. 

05/04/2016 23:14:54 :: Exception in cacheFull event handler: args=() kwargs={}
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 368, in callback
    self._startRunCallbacks(result)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 464, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/site-packages/carbon/client.py", line 114, in queueFullCallback
    events.cacheFull()
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/carbon/events.py", line 32, in <lambda>
    cacheFull.addHandler(lambda: carbon.instrumentation.increment('cache.overflow'))
exceptions.NameError: global name 'carbon' is not defined

**Comment by katzefudder** [comment]
Can also confirm the issue on 0.9.15

`25/04/2017 00:06:04 :: [console] Exception in cacheFull event handler: args=() kwargs={}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/graphite/lib/carbon/client.py", line 114, in queueFullCallback
    events.cacheFull()
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
  File "/opt/graphite/lib/carbon/events.py", line 32, in <lambda>
    cacheFull.addHandler(lambda: carbon.instrumentation.increment('cache.overflow'))
exceptions.NameError: global name 'carbon' is not defined`

**Comment by deniszh** [comment]
Hello Luke,

0.9.15 and 0.9.x branch of Graphite is outdated, please upgrade to latest
stable release (1.0.1 now)
