### ISSUE TITLE
exceptions.AttributeError: 'MetricLineReceiver' object has no attribute 'peerName'

### ISSUE THREAD

**Issue by seet61** [graphite-project/carbon#849]
A lot of errors in console.log

`09/04/2019 11:44:36 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 312, in runReactorWithLogging
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1267, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1279, in mainLoop
    self.doIteration(t)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 252, in _disconnectSelectable
    selectable.readConnectionLost(f)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 307, in readConnectionLost
    self.connectionLost(reason)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 327, in connectionLost
    protocol.connectionLost(reason)
  File "/opt/graphite/lib/carbon/protocols.py", line 155, in connectionLost
    "%s connection with %s closed cleanly" % (self.__class__.__name__, self.peerName))
exceptions.AttributeError: 'MetricLineReceiver' object has no attribute 'peerName'
`

**Comment by piotr1212** [comment]
Could be caused by #848
